name: TaskRaceChallenge
version: 1.8
api-version: 1.13
authot: nalo_
main: fr.nalo_.TaskRaceChallenge.Main
commands:
  race:
    aliases: TRC
    description: Command to start, pause, stop, skip the game
    permission: Bukkit.op